apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: eccosp-artemis
version: 4.17.0
maintainers:
  - name: "luth2"
    email: "ecp-maintainers@amprion.net"
    url: "https://www.amprion.net/"
