apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: ecp-broker
version: 4.17.0
maintainers:
  - name: "luth2"
    email: "ecp-maintenance@amprion.net"
    url: "https://www.amprion.net/"
icon: "https://www.entsoe.eu/assets/graphics/uploads/thumbnail_0a1abssgsdcolbaj.png"
